### ISSUE TITLE
Where are the updated sources?

### ISSUE THREAD

**Issue by ferozed** [phunt/avro-maven-plugin#5]
Where are the updated sources for this plugin? IT seems that maven.org has a 1.8.0 version of this plugin, whereas this repo seems to have very old code.

I am having problems building my schemas, and need to enable debug logging. No mattere what I try ( maven clean install -X etc) it does not show me which file it is failing on.

**Comment by phunt** [comment]
Hi @ferozed . Iirc upstream Apache Avro forked this project some time ago and used it as the basis for their plugin. It looks like 1.8.0 has just been released (last day as of this moment in time), perhaps checkin with the upstream community?

https://github.com/apache/avro/releases

**Comment by ferozed** [comment]
Thanks! Got it. Excellent plugin, btw!

**Comment by phunt** [comment]
NP. Enjoy. :-)
